package ejemploncapas;

import ejemploncapas.models.Persona;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class TablaPersonas extends javax.swing.JFrame {

    /**
     * Creates new form TablaPersonas
     */
    public TablaPersonas() {
        initComponents();

        // El primer índice en el Object[][] es la fila
        // y el segundo es la columna
        /*
        String[][] datos = new String[2][3];
        datos[0][0] = "Paulina";
        datos[0][1] = "1.65";
        datos[0][2] = "65";
        
        datos[1][0] = "Pedro";
        datos[1][1] = "1.71";
        datos[1][2] = "71";
         */
        String[] columnas = {"Nombre", "Estatura", "Peso"};
        ArrayList<Persona> listaPersonas = Persona.obtenerPersonas();
        String[][] datos = new String[listaPersonas.size()][columnas.length];

        for (int i = 0; i < datos.length; i++) {
            datos[i][0] = listaPersonas.get(i).nombre;
            datos[i][1] = "" + listaPersonas.get(i).estatura;
            datos[i][2] = "" + listaPersonas.get(i).peso;
        }

        DefaultTableModel tableModel = new DefaultTableModel(datos, columnas);
        tablaPersona.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersona = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Estatura", "Peso"
            }
        ));
        tablaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonaMouseClicked
        // TODO add your handling code here:
        // rowAtPoint() devuelve el número de la fila clickeada.. para llamar a rowAtPoint() tenemos
        // que pasarle por parámetro el punto específico donde se hizo click. Para esto, usamos
        // el objeto evt que viene por parámetro junto a este método MouseClicked.
        int fila = tablaPersona.rowAtPoint(evt.getPoint());
        
        ArrayList<Persona> listaPersonas = Persona.obtenerPersonas();
        Persona p = listaPersonas.get(fila);
        //JOptionPane.showMessageDialog(rootPane, p.toString());
        ActualizarPersona actualizarFrame = new ActualizarPersona(p);
        actualizarFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tablaPersonaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPersona;
    // End of variables declaration//GEN-END:variables
}
